require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # 允许ngrok域名访问（支持公网访问）
  # 方法1: 指定具体域名
  config.hosts << "blankly-pindling-bok.ngrok-free.dev"
  
  # 方法2: 使用正则表达式允许ngrok子域名
  config.hosts << /.*\.ngrok-free\.dev$/  
  config.hosts << /.*\.ngrok\.io$/        
  config.hosts << /.*\.ngrok\.app$/       
  
  # 方法3: 开发环境下允许所有主机（仅用于开发，安全性较低）
  # 如果上述方法仍有问题，可以临时使用这个方法
  config.hosts.clear if Rails.env.development?

  # 配置文件上传限制 - 支持大文件上传（500MB）
  # 注意：Rack::Timeout需要单独安装，这里只是配置说明
  # config.middleware.use Rack::Timeout, service_timeout: 600  # 10分钟超时
  
  # 配置Active Storage文件大小限制（如果使用）
  # config.active_storage.variant_processor = :mini_magick
  
  # 配置Rails日志级别以更好地调试大文件上传
  config.log_level = :info
  
  # 大文件上传配置
  config.active_storage.service = :local
  
  # 增加请求体大小限制（500MB）
  config.action_dispatch.max_request_body_size = 500.megabytes
  
  # 配置 multipart 解析器缓冲区大小
  config.middleware.use Rack::Runtime
  
  # 禁用请求日志（大文件上传时日志太大）
  # config.middleware.delete Rails::Rack::Logger
  
  # 配置更长的超时时间（需要rack-timeout gem）
  # Rails.application.config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 600
end
